### PR TITLE
Fix repo.theloop.co.kr links to public Github links (fix #9)

### LINKED ISSUE #9: Fix repo.theloop.co.kr links to public Github links
In `tests/test_util/jsonschema_validator.py`, there are multiple occurences of the domain `repo.theloop.co.kr` for referencing documentation.

However, the documentation repository `repo.theloop.co.kr` isn't available publicly.
In the meantime, the [ICON RPC Server repository](https://github.com/icon-project/icon-rpc-server/blob/master/docs/icon-json-rpc-v3.md) contains an updated JSON RPC v3 documentation.

### PR DESCRIPTION
**Pull request by Spl3en**
See #9 for discussion

### CODE REVIEW

**Comment by eunsoo-icon** [comment]
icx_*_v2 method is for ICON JSON-RPC API v2.

ICON JSON-RPC API v2 is defined at https://github.com/icon-project/icx_JSON_RPC and needs to be updated.

I will merge this pull request after ICON JSON-RPC API v2 is updated.

**Comment by eunsoo-icon** [comment]
I want to make some modification on your branch. 

Please give me a permission.

https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by Spl3en** [comment]
I believe you should be allowed to edit my branch.

**Comment by eunsoo-icon** [comment]
Since T-Bears does not support ICON JSON-RPC v2, remove the jsonschema validator for v2.

**Pull request merged**
